name: Update all parameters wiki page

on:
  workflow_dispatch:
  push:
    branches:
      - wiki_sync_parameter_md

env:
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ secrets.MY_EMAIL }}
  GIT_TOKEN: ${{ secrets.TOKEN_FOR_WIKI }}

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: run script
        run: |
          cd tool/wiki
          python --version
          python sync_runtime_parameter.py
      - name: move markdown
        run: |
          ll
          mv test.md ../../doc/wiki/Runtime-Parameters:-All.md
      - name: make a commit
        run: |
          cd ../../
          git status
          git add doc/wiki/Runtime-Parameters:-All.md
          git commit -m "[Workflow] Update all parameters wiki page"

      - name: push to branch
        run: |
          git push
